import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { SocketProvider } from "@/context/SocketContext";
import { Toaster } from "react-hot-toast"; // ✅ Import Toaster

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-white">
        <AppProvider>
          <SocketProvider>
            {children}
            {/* ✅ Add global toast container */}
            <Toaster position="top-center" reverseOrder={false} />
          </SocketProvider>
        </AppProvider>
      </body>
    </html>
  );
}
